# Generated by Django 5.2.1 on 2025-06-04 08:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DichVu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten_dich_vu', models.CharField(max_length=50)),
                ('mo_ta', models.CharField(blank=True, max_length=200)),
                ('don_gia', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='LoaiSanh',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten_loai_sanh', models.CharField(max_length=50)),
                ('gia_ban_toi_thieu', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='MonAn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten_mon_an', models.CharField(max_length=50)),
                ('don_gia', models.FloatField()),
                ('ghi_chu', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='QuyDinh',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ma_quy_dinh', models.CharField(max_length=50)),
                ('mo_ta', models.TextField(blank=True)),
                ('gia_tri', models.TextField()),
                ('dang_ap_dung', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sanh',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten_sanh', models.CharField(max_length=50)),
                ('so_luong_ban_toi_da', models.IntegerField()),
                ('trang_thai', models.CharField(choices=[('Active', 'Đang hoạt động'), ('Maintaining', 'Đang bảo trì')], default='Đang hoạt động', max_length=20)),
                ('loai_sanh', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.loaisanh')),
            ],
        ),
        migrations.CreateModel(
            name='TaiKhoan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sodienthoai', models.CharField(max_length=15)),
                ('hovaten', models.CharField(default='', max_length=100)),
                ('vaitro', models.CharField(choices=[('admin', 'Admin'), ('user', 'User')], default='user', max_length=20)),
                ('trangthai', models.CharField(choices=[('Active', 'Hoạt động'), ('Block', 'Bị khoá')], default='Hoạt động', max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TiecCuoi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten_chu_re', models.CharField(max_length=50)),
                ('ten_co_dau', models.CharField(max_length=50)),
                ('ngay_dai_tiec', models.DateField()),
                ('so_luong_ban', models.IntegerField()),
                ('so_luong_ban_du_tru', models.IntegerField()),
                ('ca', models.CharField(choices=[('Trưa', 'Trưa'), ('Tối', 'Tối')], max_length=10)),
                ('tong_tien_tiec_cuoi', models.FloatField()),
                ('tien_dat_coc', models.FloatField()),
                ('so_dien_thoai', models.CharField(max_length=15)),
                ('sanh', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.sanh')),
                ('tai_khoan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.taikhoan')),
            ],
        ),
        migrations.CreateModel(
            name='HoaDon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ngay_thanh_toan', models.DateField()),
                ('so_ngay_tre', models.IntegerField(default=0)),
                ('trang_thai', models.CharField(choices=[('Chưa đến hạn', 'Chưa đến hạn'), ('Đã thanh toán', 'Đã thanh toán'), ('Trễ hạn', 'Trễ hạn')], default='Chưa đến hạn', max_length=30)),
                ('tien_phat', models.FloatField(default=0)),
                ('tiec_cuoi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.tieccuoi')),
            ],
        ),
        migrations.CreateModel(
            name='ChiTietThucDon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('so_luong', models.IntegerField()),
                ('thanh_tien', models.FloatField()),
                ('ghi_chu', models.CharField(blank=True, max_length=200)),
                ('mon_an', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.monan')),
                ('tiec_cuoi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.tieccuoi')),
            ],
        ),
        migrations.CreateModel(
            name='ChiTietDichVu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('so_luong', models.IntegerField()),
                ('thanh_tien', models.FloatField()),
                ('dich_vu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.dichvu')),
                ('tiec_cuoi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.tieccuoi')),
            ],
        ),
    ]
