# Generated by Django 5.2.1 on 2025-06-12 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_dichvu_ten_dich_vu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taikhoan',
            name='trangthai',
            field=models.CharField(choices=[('Active', 'Hoạt động'), ('Block', 'Bị khoá')], default='Active', max_length=20),
        ),
        migrations.AlterField(
            model_name='tieccuoi',
            name='tong_tien_tiec_cuoi',
            field=models.FloatField(default=0),
        ),
    ]
