# Generated by Django 5.2.1 on 2025-06-12 09:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_taikhoan_trangthai_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tieccuoi',
            name='tai_khoan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.taikhoan'),
        ),
    ]
