# Generated by Django 5.2.1 on 2025-06-20 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_tieccuoi_tai_khoan'),
    ]

    operations = [
        migrations.AddField(
            model_name='hoadon',
            name='so_luong_ban',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='hoadon',
            name='trang_thai',
            field=models.CharField(choices=[('Chưa Thanh Toán', 'Chưa Thanh Toán'), ('Đã thanh toán', 'Đã thanh toán'), ('Trễ hạn', 'Trễ hạn')], default='Chưa Thanh Toán', max_length=30),
        ),
    ]
