# Generated by Django 5.2.1 on 2025-07-06 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_hoadon_so_luong_ban_alter_hoadon_trang_thai'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hoadon',
            name='ngay_thanh_toan',
            field=models.DateField(blank=True, null=True),
        ),
    ]
