# Generated by Django 5.2.1 on 2025-07-06 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_hoadon_ngay_thanh_toan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hoadon',
            name='tien_phat',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
